# Setup
title           : lefoy
description     : "I'm a front-end Web developer from Quebec City, Canada."
keywords        : "front-end front end web developer integrateur developpeur quebec"
url             : http://0.0.0.0:4000

author          : lefoy
name            : "lefoy"
website         : http://0.0.0.0:4000/

version         : 1.0.0
markdown        : redcarpet
highlighter     : pygments

github          : https://github.com/lefoy
twitter         : https://twitter.com/louisetiennefoy
stackoverflow   : http://stackoverflow.com/users/2141535/lefoy?tab=summary
codepen         : http://codepen.io/lefoy
repo            : https://github.com/lefoy/lefoy.github.io

# Assets
sass:
  sass_dir: _scss
  style: :compressed
