# Setup
title           : lefoy
description     : "I'm a front-end Web developer from Quebec City, Canada."
keywords        : "lefoy lefoy.net louisetiennefoy louisetienne foy web front-end frontend integrateur developer developpeur"
url             : http://lefoy.net

author          : lefoy
name            : "lefoy"
url             : https://github.com/lefoy

tagline         : "front-end web developer"
copyright       : "© 2014 lefoy - All rights reserved"

# Custom vars
version         : 1.0.0
markdown        : redcarpet
highlighter     : pygments

github          :
repo            : https://github.com/lefoy/lefoy.github.io
