# Setup
title           : lefoy
description     : "I'm a front-end Web developer from Quebec City, Canada."
keywords        : "front-end front end web developer integrateur developpeur quebec"
url             : http://lefoy.net

author          : lefoy
name            : "lefoy"
website         : http://lefoy.net/

version         : 1.0.0
markdown        : redcarpet
highlighter     : pygments

github          : https://github.com/lefoy
repo            : https://github.com/lefoy/lefoy.github.io

# Assets
sass:
  sass_dir: _scss
  style: :compressed
