name: lefoy - front-end web developer
description: Front-End Web developer from Quebec City
meta_description: "Front-End Web developer from Quebec City"

markdown: redcarpet
pygments: true
logo: true
paginate: 15

# Details for the RSS feed generator
url:            'lefoy.net'
author:         'lefoy'
