# Site informations
name: lefoy
description: Web developer from Quebec City
meta_description: "Web developer from Quebec City"

# Personal informations
github: lefoy
twitter: louisetiennefoy
stackoverflow: lefoy

# Site settings
markdown: redcarpet
highlighter: pygments
logo: /assets/images/logo.jpg
paginate: 15

# Details for the RSS feed generator
url: 'lefoy.net'
author: 'lefoy'

# Github informations
repository: 'https://github.com/lefoy/lefoy.github.io'
